@startuml

class app.App {
	{method}  {static} +main ( args : String[] ) : void
	{method}  {static} +sendCloseSignal () : void
}


class app.common.network.Client {
}


class app.common.util.Config {
	{field} {static} +LOCALPORT : int
	{field} {static} +ONLINEIP : String
	{field} {static} +ONLINEPORT : int
	{field} {static} +SERVERJAR : Path
}


class app.common.util.ScannerSingleton {
	{method}  {static} +closeInstance () : void
}


class app.common.util.WHYsonParser {
	{method} +getValue ( param : String ) : String
}


class app.common.widgets.cliMenu.CLIMenu {
	{method} +addOption ( option : Option ) : void
	{method} +clearScreen () : void
	{method} +printOptionsList () : void
	{method} +runOption ( scanner : Scanner ) : void
}


class app.common.widgets.cliMenu.parts.Option {
	{method} +run ( scanner : Scanner ) : void
}


interface app.common.widgets.cliMenu.parts.ToExecute {
	{method}  {abstract} +execute () : void
}


class app.games.TikTakToe {
}


abstract class app.games.common.Game {
}


class app.games.common.GameSession {
}


class app.games.players.Bot {
}


class app.games.players.Local {
}


class app.games.players.Remote {
}


class app.menus.GameMenu {
	{method} +open () : void
}


class app.menus.MainMenu {
	{method} +open () : void
}


class app.menus.common.MenuContext {
}


interface app.menus.common.MenuState {
	{method}  {abstract} +open () : void
}




app.App -->  app.App : INSTANCE
app.common.widgets.cliMenu.CLIMenu "1" o-- "0..*"  app.common.widgets.cliMenu.parts.Option : optionsList
app.common.widgets.cliMenu.parts.Option -->  app.common.widgets.cliMenu.parts.ToExecute : function
app.menus.GameMenu ..|>  app.menus.common.MenuState
app.menus.MainMenu ..|>  app.menus.common.MenuState
app.menus.common.MenuContext -->  app.menus.common.MenuContext : INSTANCE
app.menus.common.MenuContext -->  app.menus.common.MenuState : state


@enduml